ALTER TABLE title ENGINE=MyISAM;
ALTER TABLE aka_title ENGINE=MyISAM;
ALTER TABLE name ENGINE=MyISAM;
ALTER TABLE aka_name ENGINE=MyISAM;
ALTER TABLE char_name ENGINE=MyISAM;

ALTER TABLE cast_info ENGINE=MyISAM;
ALTER TABLE movie_info ENGINE=MyISAM;
ALTER TABLE movie_info_idx ENGINE=MyISAM;
ALTER TABLE person_info ENGINE=MyISAM;
ALTER TABLE keyword ENGINE=MyISAM;
ALTER TABLE movie_keyword ENGINE=MyISAM;

ALTER TABLE company_name ENGINE=MyISAM;
ALTER TABLE movie_companies ENGINE=MyISAM;
ALTER TABLE company_type ENGINE=MyISAM;
ALTER TABLE comp_cast_type ENGINE=MyISAM;
ALTER TABLE complete_cast ENGINE=MyISAM;

ALTER TABLE info_type ENGINE=MyISAM;
ALTER TABLE kind_type ENGINE=MyISAM;
ALTER TABLE role_type ENGINE=MyISAM;
ALTER TABLE link_type ENGINE=MyISAM;
ALTER TABLE movie_link ENGINE=MyISAM;

